# Generated by Django 2.0.6 on 2018-06-29 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_id_hex', models.CharField(default='', max_length=30, unique=True)),
                ('color_name', models.CharField(default='', max_length=100)),
                ('is_light', models.BooleanField(default=True)),
                ('color_tendency', models.CharField(default='', max_length=10)),
                ('is_saturated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color_Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_many_colors', models.IntegerField(default=0)),
                ('group_tendency', models.CharField(default='', max_length=10)),
                ('colors', models.ManyToManyField(to='polls.Color')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=100)),
                ('file_field', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_color_groups', models.ManyToManyField(to='polls.Color_Groups')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
