# Generated by Django 2.0.6 on 2018-06-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180620_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Color_Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.ManyToManyField(to='polls.Color')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('liked_color_groups', models.ManyToManyField(to='polls.Color_Groups')),
            ],
        ),
    ]
