# Generated by Django 2.0.7 on 2018-07-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_cluster_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color_Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_id', models.IntegerField(max_length=20)),
                ('cg_id', models.IntegerField(max_length=20)),
                ('c_count', models.IntegerField(max_length=20)),
                ('c_light', models.IntegerField(max_length=20)),
                ('c_satur', models.IntegerField(max_length=20)),
            ],
        ),
    ]
