# Generated by Django 2.0.6 on 2018-06-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180626_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color_id',
            new_name='color_id_hex',
        ),
        migrations.AddField(
            model_name='color',
            name='color_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='color',
            name='is_dark',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='color_groups',
            name='tendency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='color_groups',
            name='how_many_colors',
            field=models.IntegerField(default=0),
        ),
    ]
