# Generated by Django 2.0.7 on 2018-07-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_color_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color_cluster',
            name='c_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='color_cluster',
            name='c_light',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='color_cluster',
            name='c_satur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='color_cluster',
            name='cg_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='color_cluster',
            name='color_id',
            field=models.IntegerField(),
        ),
    ]
