# Generated by Django 2.0.6 on 2018-06-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180626_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='is_dark',
            new_name='is_light',
        ),
        migrations.RenameField(
            model_name='color_groups',
            old_name='tendency',
            new_name='group_tendency',
        ),
        migrations.AddField(
            model_name='color',
            name='color_tendency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='color',
            name='is_saturated',
            field=models.BooleanField(default=True),
        ),
    ]
