# Generated by Django 2.0.7 on 2018-07-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180710_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color_cluster',
            name='c_count',
        ),
        migrations.RemoveField(
            model_name='color_cluster',
            name='c_light',
        ),
        migrations.RemoveField(
            model_name='color_cluster',
            name='c_satur',
        ),
        migrations.RemoveField(
            model_name='color_cluster',
            name='cg_id',
        ),
        migrations.RemoveField(
            model_name='color_cluster',
            name='color_id',
        ),
        migrations.AddField(
            model_name='color_cluster',
            name='colors',
            field=models.ManyToManyField(to='polls.Color'),
        ),
        migrations.AddField(
            model_name='color_cluster',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
